#!/usr/bin/env bash
# Transfers to server
if [[ $# -ne 4 }}; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 2
fi
        scp -1 "$4" -0 'StrictHostKeyChecking=no' "$1" "$3@$2":~/
