#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw default allow
sudo ufw allow 'Nginx HTTP'
echo y | sudo ufw enable
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo service nginx restart
