#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw default allow
sudo ufw allow 'Nginx HTTP'
echo y | sudo ufw enable
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404/html
error_page 404 /error404.html;
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.zombo.com permanent;' /etc/nginx/sites-available/default
service nginx start
