#!/usr/bin/env bash
# This is a bash script to display 10 times with iteration of hi after 9th line"
x=1
while [ $x -le 10 ]
do
  echo "Holberton School"
  x=$(( x + 1 ))
  if ( x = 9 );
  then echo "Hi"
  fi
done
