#!/usr/bin/env bash
# THis is a while loop with if, elif, and else"
x=0
while [ $x -lt 10 ]
do
x=$(( x + 1 ))
  if [ $x == 4 ]
  then  
  echo "bad luck"
  elif [ $x == 8 ]
  then 
  echo "good luck"
  else 
  echo "Holberton School"
  fi
done
