#!/usr/bin/env bash
# This is a script that displays numbers 1 to 20 along with bad luck iteration.
x=0
while [ $x -lt 20 ]
do
x=$(( x + 1 ))
echo $x
case $x in
4)
echo "bad luck from China" ;;
9)
echo "bad luck from Japan" ;;
17)
echo "bad luck from Italy" ;;
esac
done
