#!/usr/bin/env bash
# Installs and configures HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "

frontend haproxynode
    bind *:80
    mode http
    default_backend backendnodes

backend backendnodes
    balance roundrobin
    server 3447-web-01 34.139.222.255
    server 3447-web-02 34.139.229.234" > etc/haproxy/haproxy.cfg

sudo service haproxy restart

